# Key settings (must edit)
project_title: Choochoo 2022 induction repository
project_repo: lucydot/Induction_checklist
admins:
- lucydot
- choochoo-bot
instructors:
- lucydot
students:
- lucydot
- choochoo-bot
web_address: https://lucydot.github.io/Induction_checklist

# User options (may edit)
questions: true
votes_required: 3
gh-pages: true
gh-pages_branch: gh-pages



